#### Imports

In [23]:
import numpy as np
import matplotlib.pyplot as plt

#### Function to create a blur matrix

In [24]:
def create_matrix(
        size
):  # first we need a function that creates empty matrices of the size we want (np.empty is not readable)
    if int(size) > 0:
        s = 1
        mat = []
        while s <= size:
            mat.append([0.0] * size) #the data type of matrix elements is set on creation, so float instead of int
            s += 1
        mat = np.array(mat)
    return mat

def create_blur_matrix(size):
    blurred_matrix = create_matrix(size)             # create a zeroes matrix of the required size
    if size > 1:
        for i in range(0, blurred_matrix.shape[1]):  # go through all columns of the matrix
            if i == 0:                               # set the edge case for the upper left corner
                blurred_matrix[i,i] = 0.8
                blurred_matrix[1,i] = 0.2
            elif i == (blurred_matrix.shape[1] - 1): # set the edge case for the bottom right corner
                blurred_matrix[i, i] = 0.8
                blurred_matrix[i-1, i] = 0.2
            else:
                blurred_matrix[i,i] = 0.6
                blurred_matrix[i-1,i] = 0.2
                blurred_matrix[i+1,i] = 0.2

        return blurred_matrix


In [25]:
M = create_blur_matrix(12)

#### Create a vector B of length 12 that represents the number of birthdays that you have in that month.

In [26]:
B = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
print(B)

[0 0 0 0 0 0 0 0 0 0 0 1]


#### Create a vector C of length 12 that represents the number of birthdays that your parents have in that month.

In [27]:
C = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0])
print(C)

[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.8]


#### Blur B once, print

In [16]:
bBlur = np.matmul(M, B)
print(bBlur)

[0 0 0 0 0 0 0 0 0 1 1 0]


#### Blur C once, print

In [17]:
cBlur = np.matmul(M, C)
print(cBlur)

[0.  0.  0.  0.  0.  0.  0.  0.  0.2 0.8 0.8 0.2]


####  Compute D = (B+C)

In [18]:
D = B + C
print(D)

[0 0 0 0 0 0 0 0 0 1 1 1]


#### Compute D2 by blurring D twice, print

In [33]:
D1 = np.matmul(M, np.matmul(M, D))
print(D2)

[0.   0.   0.   0.   0.   0.   0.   0.04 0.28 0.72 0.96 1.  ]


#### Compute B2 by blurring B twice, print

In [31]:
B2 = np.matmul(M, np.matmul(M, B))
print(B2)

[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.04 0.28 0.68]
[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.04 0.28 0.68]


#### Compute C2 by blurring C twice, print

In [32]:
C2 = np.matmul(M, np.matmul(M, C))
print(C2)

[0.   0.   0.   0.   0.   0.   0.   0.04 0.28 0.68 0.68 0.32]


#### Compute BC2 by adding B2 and C2, print

In [34]:
BC2 = B2 + C2
print(BC2)

[0.   0.   0.   0.   0.   0.   0.   0.04 0.28 0.72 0.96 1.  ]


#### Is BC2 always equal to D2? Find a counterexample, or provide an argument why these two must be equal.

BC2 will always be equal to D2 since matrx multiplication is distributive. This can be proved as follows:

```
B2 = M * (M * B)
C2 = M * (M * C)

B2 + C2 = M * (M * B) + M * (M * C)
B2 + C2 = M * (M*B + M*C) ...based on distributivity

B2 + C2 = M * (M*(B + C)) and D2 = M * (M * (B + C))

Thefore B2 + C2 = D2
```
